---
- hosts: localhost
  connection: local

  tasks:
    - name: install dnsmasq
      homebrew:
        name: dnsmasq
        state: present

    - name: configure dnsmasq
      copy:
        dest: "/usr/local/etc/dnsmasq.conf"
        src: "files/dnsmasq.conf"
        owner: "{{ user }}"

    - name: configure DNS resolver
      copy:
        dest: "/etc/resolver/"
        src: "files/resolver/"
        owner: "{{ user }}"