---
- hosts: localhost
  user: jgeerling
  connection: local

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.homebrew

  tasks:
    - name: create folder for LaunchAgents
      file:
        path: ~/Library/LaunchAgents
        state: directory
    - name: create symlinks for LaunchAgents
      file:
        path: "/Library/LaunchDaemons/homebrew.mxcl.{{ item.key }}.plist"
        state: link
        src: "/usr/local/opt/{{ item.value }}.plist"
      with_dict:
        elasticsearch17: elasticsearch17/homebrew.mxcl.elasticsearch17
        mariadb: mariadb/homebrew.mxcl.mariadb
        nginx: nginx/homebrew.mxcl.nginx
        php56: php56/homebrew.mxcl.php56
        php55: php55/homebrew.mxcl.php55

    - name: 'nginx: set listen port to 80'
      lineinfile:
        dest: /usr/local/etc/nginx/nginx.conf
        regexp: "^        listen.*8080"
        line: "listen 80;"

    - name: 'configure nginx'
      template:
        dest: '/usr/local/etc/nginx/nginx.conf'
        src: 'files/nginx/nginx.conf.j2'
        owner: "{{ user }}"

    - name: 'configure php-fpm'
      template:
        dest: "/usr/local/etc/php/{{ item }}/php-fpm.conf"
        src: "files/php{{ item | replace('.', '') }}/php-fpm.conf.j2"
        owner: "{{ user }}"
      with_items:
        - 5.5
        - 5.6

    - name: 'create configuration folders for php-fpm'
      file:
        path: "/usr/local/etc/php/{{ item }}/fpm.d"
        state: directory
        owner: "{{ user }}"
      with_items:
        - 5.5
        - 5.6

    - name: 'configure mariadb'
      template:
        dest: '/usr/local/etc/my.cnf'
        src: 'files/mariadb/my.cnf.j2'
        owner: "{{ user }}"

    - name: 'create configuration folders for nginx'
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ user }}"
      with_items:
        - /usr/local/etc/nginx/sites-available
        - /usr/local/etc/nginx/sites-enabled

    - name: set permissions
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ user }}"
        group: staff
        mode: 0775
        recurse: yes
      with_items:
        - /usr/local/var/log/
        - /usr/local/etc/nginx/
        - /usr/local/var/run/
        - /usr/local/var/mysql/



#To have launchd start homebrew/versions/elasticsearch17 at login:
#  mkdir -p ~/Library/LaunchAgents
#  ln -sfv /usr/local/opt/elasticsearch17/*.plist ~/Library/LaunchAgents
#Then to load homebrew/versions/elasticsearch17 now:
#  launchctl load ~/Library/LaunchAgents/homebrew.mxcl.elasticsearch17.plist
#Or, if you don't want/need launchctl, you can just run:
#  elasticsearch --config=/usr/local/opt/elasticsearch17/config/elasticsearch.yml


# /usr/local/opt/php56/sbin/php-fpm --fpm-config /usr/local/etc/php/5.6/php-fpm.conf
