---

- name: debug Instance Notification
  debug: msg="Remove this when installing for the first time..."
  tags: instance

- name: "install packages"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release.noarch
    - ansible.noarch
    - autoconf.noarch
    - bash-completion.noarch
    - git.x86_64
    - gpgme.x86_64
    - zsh.x86_64
    - firefox.x86_64
