---
- name: "{{ name }}: create vhost folder"
  file:
    path: "{{ webdev_projectspath }}{{ name }}"
    state: directory
    owner: "{{ webdev_nginx_user }}"
    group: "{{ webdev_nginx_group }}"
  tags: instance

- name: "{{ name }}: add vhost configuration"
  template:
    dest: "{{ webdev_homebrew_rootpath }}etc/nginx/sites-available/{{ name }}.conf"
    src: 'applications/{{ application }}.conf.j2'
    owner: "{{ webdev_nginx_user }}"
    group: "{{ webdev_nginx_group }}"
  notify: restart nginx
  tags: instance

- name: "{{ name }}: create symlink for vhost configuration"
  file:
    path: "{{ webdev_homebrew_rootpath }}etc/nginx/sites-enabled/{{ name }}.conf"
    state: link
    src: "{{ webdev_homebrew_rootpath }}etc/nginx/sites-available/{{ name }}.conf"
  notify: restart nginx
  tags: instance