---
- name: install nginx
  yum:
    name: nginx.x86_64
    state: present
  notify: restart nginx
  tags: setup

- name: create folders for vhosts
  file:
    path: "{{ webdev_projectspath }}"
    state: directory
    owner: "{{ webdev_nginx_user }}"
    group: "{{ webdev_nginx_group }}"
  tags: setup

- name: configure nginx
  template:
    dest: "{{ webdev_yum_rootpath }}etc/nginx/nginx.conf"
    src: 'nginx.conf.j2'
    owner: "{{ webdev_nginx_user }}"
    group: "{{ webdev_nginx_group }}"
  notify: restart nginx
  tags: setup

- name: create vhost configuration folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ webdev_nginx_user }}"
    group: "{{ webdev_nginx_group }}"
  with_items:
    - "{{ webdev_yum_rootpath }}etc/nginx/sites-available"
    - "{{ webdev_yum_rootpath }}etc/nginx/sites-enabled"
  notify: restart nginx
  tags: setup

- name: create instance
  include: create_instance.yml
  when: name is defined
