---
- name: install selenium
  homebrew:
    name: selenium-server-standalone
    state: present
  notify: restart selenium
  tags: setup

- name: create folder for LaunchAgents
  file:
    path: "{{ webdev_home }}Library/LaunchAgents"
    state: directory
    owner: "{{ webdev_user }}"
  tags: setup

- name: create symlink for LaunchAgent
  file:
    path: "{{ webdev_home }}Library/LaunchAgents/homebrew.mxcl.selenium-server-standalone.plist"
    state: link
    src: "{{ webdev_homebrew_rootpath }}opt/selenium-server-standalone/homebrew.mxcl.selenium-server-standalone.plist"
  notify: restart selenium
  tags: setup
