---
- name: configure dnsmasq
  template:
    dest: "{{ webdev_homebrew_rootpath }}etc/dnsmasq.conf"
    src: "dnsmasq.conf.j2"
    owner: "{{ webdev_user }}"
    group: "{{ webdev_group }}"
  notify: restart dnsmasq

- name: create resolver folder
  file:
    path: /etc/resolver/
    state: directory
    owner: "{{ webdev_user }}"
    group: "{{ webdev_group }}"

- name: configure DNS resolver
  template:
    dest: "/etc/resolver/{{ item.key }}"
    src: "resolver.j2"
    owner: "{{ webdev_user }}"
    group: "{{ webdev_group }}"
  with_dict: "{{ webdev_dnsmasq_domains }}"
  notify: restart dnsmasq
