---
- name: "PHP {{ version }}: install "
  yum:
    name: "{{ webdev_php_versions[version].package }}"
    state: present
  notify: restart php-fpm
  tags: setup

- name: "PHP {{ version }}: install extensions"
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ webdev_php_versions[version].extension_packages }}"
  notify: restart php-fpm
  tags: setup

- name: "PHP {{ version }}: create folders in /etc/php.d/"
  file:
    path: "{{ webdev_yum_rootpath }}etc/php.d/{{ version }}"
    state: directory
    owner: "{{ webdev_php_user }}"
    group: "{{ webdev_php_group }}"
  notify: restart php-fpm
  tags: setup

- name: "PHP {{ version }}: configure php-fpm"
  template:
    dest: "{{ webdev_yum_rootpath }}etc/php.d/{{ version }}/php-fpm.conf"
    src: "php{{ version | replace('.', '') }}/php-fpm.conf.j2"
    owner: "{{ webdev_php_user }}"
    group: "{{ webdev_php_group }}"
  notify: restart php-fpm
  tags: setup

- name: "PHP {{ version }}: add additional configuration for php-fpm"
  copy:
    dest: "{{ webdev_yum_rootpath }}etc/php.d/{{ version }}/conf.d/"
    src: "php{{ version | replace('.', '') }}/conf.d/"
    owner: "{{ webdev_php_user }}"
    group: "{{ webdev_php_group }}"
  notify: restart php-fpm
  tags: setup

- name: "PHP {{ version }}: remove default configuration folder"
  file:
    path: "{{ webdev_yum_rootpath }}etc/php.d/{{ version }}/php-fpm.d"
    state: absent
  tags: setup

- name: "PHP {{ version }}: create configuration folders for php-fpm pools"
  file:
    path: "{{ webdev_yum_rootpath }}etc/php.d/{{ version }}/fpm.d"
    state: directory
    owner: "{{ webdev_php_user }}"
    group: "{{ webdev_php_group }}"
  notify: restart php-fpm
  tags: setup
