---
- name: PHP 5.6
  include: install_php.yml
  vars:
    version: '5.6'

- name: PHP 7.0
  include: install_php.yml
  vars:
    version: '7.0'

- name: "install packages"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - composer.noarch
    - php-phpunit-PHPUnit.noarch
    #- behat
  tags: setup