---

- name: "add homebrew tap 'php'"
  homebrew_tap:
    tap: "homebrew/php"
    state: present
  tags: setup

- name: PHP 5.4
  include: install_php.yml
  vars:
    version: '5.4'

- name: PHP 5.5
  include: install_php.yml
  vars:
    version: '5.5'

- name: PHP 5.6
  include: install_php.yml
  vars:
    version: '5.6'

- name: PHP 7.0
  include: install_php.yml
  vars:
    version: '7.0'

- name: "install packages"
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - composer
    - phpunit
    - behat
  tags: setup