---
- name: install zsh
  yum:
    name: zsh.x86_64
    state: present

- name: install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "{{ webdev_dotfiles_home }}.oh-my-zsh"

- name: add zsh to available shells
  lineinfile:
    dest: /etc/shells
    line: "{{ webdev_homebrew_rootpath }}bin/zsh"
    state: present

- name: set default shell
  user:
    name: "{{ webdev_dotfiles_user }}"
    group: "{{ webdev_dotfiles_group }}"
    shell: /bin/zsh

- name: set permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ webdev_dotfiles_user }}"
    group: "{{ webdev_dotfiles_group }}"
    mode: u=rwX,g=rX,o=rX
    recurse: yes
  with_items:
    - "{{ webdev_dotfiles_home }}.oh-my-zsh"

- name: create folder for dotfiles
  file:
    path: "{{ webdev_dotfiles_home }}.profile.d//"
    state: directory
    owner: "{{ webdev_dotfiles_user }}"
    group: "{{ webdev_dotfiles_group }}"
    mode: u=rwX,g=rX,o=rX

- name: copy dotfiles
  template:
    src: "{{ item }}"
    dest: "{{ webdev_dotfiles_home }}{{ item | regex_replace('.j2','') }}"
    owner: "{{ webdev_dotfiles_user }}"
    group: "{{ webdev_dotfiles_group }}"
    mode: u=rwX,g=rX,o=rX
  with_items:
    - ".zshrc.j2"
    - ".profile.d/alias.j2"
