---
- name: install zsh
  homebrew:
    name: zsh
    state: present

- name: install oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: "{{ webdev_dotfiles_home }}.oh-my-zsh"

- name: set permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ webdev_dotfiles_user }}"
    group: "{{ webdev_dotfiles_group }}"
    mode: u=rwX,g=rX,o=rX
    recurse: yes
  with_items:
    - "{{ webdev_dotfiles_home }}.oh-my-zsh"

- name: copy dotfiles
  template:
    src: "{{ item }}"
    dest: "{{ webdev_dotfiles_home }}{{ item | basename | regex_replace('.j2','') }}"
    owner: "{{ webdev_dotfiles_user }}"
    group: "{{ webdev_dotfiles_group }}"
    mode: u=rwX,g=rX,o=rX
  with_fileglob:
    - ../templates/.*.j2
    - ../templates/*.j2
